### PR TITLE
Improve plugin support

### LINKED ISSUE #132: plugins usage and inclusion redesign
Problem statement
------------------

At the moment, plugins can be included in reveal-hugo with these 4 steps:

* include the plugin in the site tree
* add a [params.]reveal_hugo.plugins array to the front matter (or config.toml)
* create a head.html layout
* add appropriate css to that new file.

This is ok, but some [users](#96) seem to feel this is unwieldy.

Also, in the new reveal-js upgrade, a new registration mechanism is introduced which needs the Plugin object to crystalize plugin registration. @chrisreddington voiced [seeking guidance](https://github.com/dzello/reveal-hugo/pull/115#discussion_r814929622) on this fact. 

Proposition
-----------

I believe that by enhancing the plugins array, we can prepare for a better upgrade route and support legacy. 

I propose to make the plugins slice a slice of objects with these fields:

```toml
[[plugins]]
name = "RevealNotes" # used to give the plugin the name used for registration
source =  "reveal-js/plugin/notes/notes.js" # "relative/path/to/plugin.js"
css = "relative/path/to/plugin.css"
local = [true|false] # override any cdn prefix that would be configured
```

Consequences
---------------

By packing more information, reveal-hugo is also able to do more:

* It can remove the need for the user to add a partial layout just for specifying css (the build step can do that for the user)
* We have enough information to fix questioning raised in #115, as we can register plugins with the now required plugin name
* Cdn based plugins can be consumed (there is currently a limitation in the docs about this)
* Default plugins and user plugins receive the same treatment and are registered in the same way.
* Upgrading to reveal 4 is facilitated

We should worry about current implementations that specify plugins by path only, and support those for backward compatibility (we can infer that the current object is a string). But the name will be needed for reveal 4.0+ support in the future.

@dzello WDYT?

### PR DESCRIPTION
**Pull request by davidovich**
This PR enables a new plugin description format that will enable future updates to reveal-js and its new plugin mechanism.

We change the plugin from a mere javascript plugin string path to a complex object. With this object, we can dispatch css, javascript and support CDN loading.

The complete object format is:

```toml
name = ""
source = "static/or/content/relative/javascript/path"
css = "optional static/or/content/relative/javascript/path"
verbatim = false # should the path be tried with the cdn prefix or not. Verbatim means as-is.
order = 0 # int order in which the <script> tags are added to the generated html"
```

fixes #132

### CODE REVIEW

**Comment by davidovich** [comment]
HI @dzello, is there something more I can do to make this a reality ? I'd like to tackle upgrading reveal to latest by continuing work of #115

**Comment by dzello** [comment]
@davidovich Thanks for moving this ahead and sorry about the delay on my end.

Is there anything we need to consider from a migration or backwards compatibility standpoint before merging this in? Will old sites continue to work or do we need to add something to the README on how to update them?

**Comment by davidovich** [comment]
Hi @dzello, and happy holidays!

One of your requirements was that the introduction of the enhanced data-structure should be backward compatible, and that is exactly what the code implements.  So for your concern on the migration policy, there is none, it is a drop-in, compatible change.

I am not familiar with hugo theme testing techniques or even if these exist :-/, but have cloned these repos from [a search](https://github.com/search?q=reveal_hugo&type=code) on `reveal_hugo` config key (taken somewhat randomly) and put these repos as siblings to `exampleSite`. I changed their config.toml to use the in-repo, current version of reveal-hugo.

* https://github.com/slashpai/presentations
* https://github.com/bruxisma/rustconf-2019
* https://github.com/wiggins-jonathan/stevenvukcevich.com
* https://github.com/maelle/2022-rpkgdev-sicss

All these sites predate the plugin mechanism and load correctly. To test, I build the site before and after this MR, and looked at rendering diffs. Below is a typical diff observed in stevenvukevich.com:

image

Others (2022-rpkdev-siccs) have been been seemingly built from a template that deactivates default plugins, and there the output is what we would expect:

image

With these random checks, I am pretty confident that the changes are sane :-). Please advise on further testing you would like to suggest.

### Note

Some of these use hugo modules and I needed to temporarily make reveal-hugo be a module for easy testing:

In reveal-hugo, add a go.mod:

```go
module github.com/dzello/reveal-hugo

go 1.19
```

in the go.mod of the consuming repo add a replace directive: 

```go
replace github.com/dzello/reveal-hugo => ../
```

**Comment by dzello** [comment]
@davidovich Happy new year to you! I appreciate the work that you've put into reveal-hugo in 2022 and invite you to continue in 2023 :) I'll go ahead and merge PR in. Thanks for the info and extensive testing on backwards compatibility. I'm not aware if there are any specific theme testing techniques either, but it feels like we've done the homework here with the example site and the ones you found.

**Comment by davidovich** [comment]
Thanks @dzello I will be on the lookout for any bugs raised and will fix them promptly if they are reported.

**Pull request merged**
