### PR TITLE
Add circleci for verifying build of template changes

### PR DESCRIPTION
**Pull request by jerdog**
Figured I would put together a quick, and free for Open Source projects, CircleCI config to test that any changes made build with the exampleSite correctly.

### CODE REVIEW

**Comment by dzello** [comment]
@jerdog Thanks! I need to figure out why Netlify is unhappy and then I'll merge this in.

**Comment by jerdog** [comment]
> @jerdog Thanks! I need to figure out why Netlify is unhappy and then I'll merge this in.

Ahh yes, the rabbit hole of "wtf is going on?"

**Comment by dzello** [comment]
I re-ran the build from Netlify and it seemed to work, even though it didn't update the checks here. I've merged it and will see what happens now. Thanks again @jerdog!

**Comment by dzello** [comment]
@jerdog Any idea why the CircleCI badge in the README is broken?

**Comment by jerdog** [comment]
Ahh, yes. You need to go to https://app.circleci.com/projects/project-dashboard/github/dzello/ and then "Follow" this project in order for it to start running builds via the config.

**Comment by dzello** [comment]
@jerdog Ah ha - thanks. I set up the project and got this error in the `build site` stage. Do we need to add go somewhere in the config?

CleanShot 2023-01-14 at 23 16 44@2x

**Comment by jerdog** [comment]
That is quite odd, given that the exact same config runs just fine

https://app.circleci.com/pipelines/github/jerdog/reveal-hugo/16/workflows/daa0ff9d-fe70-446f-a69e-1604e829ffdd

**Comment by deining** [comment]
> That is quite odd,

No, I have an explanation.

> given that the exact same config runs just fine
> 
> https://app.circleci.com/pipelines/github/jerdog/reveal-hugo/16/workflows/daa0ff9d-fe70-446f-a69e-1604e829ffdd

On the mentioned repo commit, the example site expects the theme under the `themes` directory. This was changed afterwards, the example site now pulls in the theme as hugo module. For doing so, the `go` binary is needed. That's why the CI run fails with HEAD of repo.

> you can try adding the GO orb... but that shouldn't be doing this
> 
> ```yaml
>   go: circleci/go@1.7.2
> ```

Adding a recent version of go (ideally 1.9.x) will almost certainly resolve this issue.

**Pull request merged**
