### PR TITLE
Cache bust the custom theme

### PR DESCRIPTION
**Pull request by BrianGon**
I found it useful to cache bust the custom theme, especially when working on the design while developing the presentation.

### CODE REVIEW

**Comment by dzello** [comment]
Thanks for the PR! I can definitely see that being useful. With the new Hugo asset pipeline functions, I think we could actually implement this with a fingerprint instead of the Unix.now. That way it's not busted if the contents didn't change.

This [blog post](https://regisphilibert.com/blog/2018/07/hugo-pipes-and-asset-processing-pipeline/) describes how to add the fingerprint - see the "Fingerprinting with .Fingerprint". Want to give it a look and see if that can be done here?

**Comment by BrianGon** [comment]
Interesting, thanks! I'll look into implementing it that way instead and get back to you.

**Comment by dzello** [comment]
@BrianGon Happy new year! Did you get a chance to look at the fingerprinting method yet?

**Comment by BrianGon** [comment]
@dzello Happy new year! Not quite, I've had to divert my attention to some other projects during the holidays. I'll dive back into the assets in the project I use reveal in and add the fingerprint to my PR.

**Comment by BrianGon** [comment]
I've added the fingerprinting and tested it on the example site locally. The netlify build fails because I think Hugo version 0.42.2 doesn't support the pipeline feature.

> 10:52:34 PM: Installing Hugo 0.42.2

To use the fingerprinting the string has to be a resource. To do that you also have to reassign the default resources directory that hugo looks into-- from "assets" to "static" in the config. And then we have to .gitignore a "resources" folder that gets generated on build.

Implementing it does add a layer of complexity to the code that I'm not sure warrants the one feature as its applied here. I can definitely see its usefulness in larger groups of assets. So it's your call if this PR seems useful to add to the main project! :)

**Comment by dzello** [comment]
@BrianGon thanks for looking into that. Ahhhh yeah, that's right, Netlify doesn't yet support the Hugo extended binary for building assets. Currently the recommendation from Netlify is just to check in the resources folder (I do this on a few sites) but that is messier and leads to really noisy commit diffs when asset changes are involved.

I think this is getting fixed in the next month or two, so let's wait until then and then we could make the change. Rather than change the assets directory to static, we can just move the files in static that need processing into the assets directory, then add a .gitignore for resources. I'll leave this open for now, let's pick it up once Netlify makes that change. Sound good?

**Comment by BrianGon** [comment]
I agree, will be much cleaner that way and once Netlify implements it we can move those files over to assets properly.

**Comment by dzello** [comment]
I gave this some more thought and I don't think we want reveal-hugo to fail for the version of Hugo that isn't compiled with the pipeline. If someone needs the cachebusting, please implement it referring to the example above.

**Pull request closed without merging**
